# Generated by Django 3.1.1 on 2020-10-08 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0011_auto_20201006_1445'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTransaction', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='customer.customer')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='product.product')),
            ],
            options={
                'db_table': 'Buy',
            },
        ),
    ]
