# Generated by Django 3.1.1 on 2020-09-16 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zipCode', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('spouseName', models.CharField(max_length=50)),
                ('spouseOccupation', models.CharField(max_length=50)),
                ('childrenNum', models.IntegerField()),
                ('motherName', models.CharField(max_length=50)),
                ('motherOccupation', models.CharField(max_length=50)),
                ('fatherName', models.CharField(max_length=50)),
                ('fatherOccupation', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('religion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.person')),
                ('dateRegistered', models.DateField()),
            ],
            bases=('customer.person',),
        ),
    ]
