# Generated by Django 3.1.1 on 2020-09-16 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200916_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateRegistered',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
