# Generated by Django 3.1.1 on 2020-09-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200929_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
